# ProvPy interoperability tests
#
# This job assumes the following packages have been installed (these
# are provided by the Travis CI build environment,
# http://docs.travis-ci.com/user/ci-environment):
#
# git
# curl
# Python 2 and 3
## ProvPy prerequisites
# graphviz 

language: python

python:
  - 2.7
  - 3.4

before_install:
  - echo "Getting test cases..."
  - git clone https://github.com/mikej888/provtoolsuite-testcases testcases
  - echo "Installing ProvPy dependencies..."
  - sudo apt-get -y install zlib1g-dev
  - sudo apt-get -y install libxslt1-dev
  - echo "Getting ProvPy..."
# Source ProvPy
  - git clone https://github.com/trungdong/prov ProvPy
  - cd ProvPy
  - python setup.py install
  - ./scripts/prov-convert --version
  - ./scripts/prov-compare --version
  - cd ..
# Package ProvPy
#  - pip install prov
#  - prov-convert --version
#  - prov-compare --version
  - echo "Getting test harness..."
  - git clone https://github.com/mikej888/provtoolsuite-interop-test-harness test-harness
  - cd test-harness
  - pip install -r requirements.txt
  - echo "Creating local test harness configuration files..."
  - echo "PROV_TEST_CASES_DIR=$TRAVIS_BUILD_DIR/testcases" > config.properties
  - echo "PROV_LOCAL_CONFIG_DIR=$TRAVIS_BUILD_DIR/test-harness/localconfig" >> config.properties
# Source ProvPy
  - echo "PROVPY_CONVERT_EXE=python" >> config.properties
  - echo "PROVPY_COMPARE_EXE=python" >> config.properties
  - echo "PROVPY_SCRIPTS_DIR=$TRAVIS_BUILD_DIR/ProvPy/scripts" >> config.properties
# Package ProvPy
#  - echo "PROVPY_CONVERT_EXE=prov-convert" >> config.properties
# Since prov-convert is executable, blank out the script name argument
#  - echo "PROVPY_SCRIPTS_DIR/prov-convert,=" >> config.properties
#  - echo "PROVPY_COMPARE_EXE=prov-compare" >> config.properties
# Since prov-convert is executable, blank out the script name argument
#  - echo "PROVPY_SCRIPTS_DIR/prov-compare,=" >> config.properties
  - cat config.properties
  - mkdir localconfig
  - python prov_interop/customise-config.py config localconfig config.properties
  - echo "Test configuration..."
  - cat localconfig/*

script: 
  - nosetests -v prov_interop.interop_tests.test_provpy
