language: python

python:
  - 2.7

before_install:
  - PWD=`pwd`
  - mkdir $PWD
  - echo "Getting test cases..."
  - TESTCASES=$PWD/testcases
  - git clone https://github.com/mikej888/provtoolsuite-testcases $TESTCASES
  - echo "Installing ProvPy dependencies..."
  - sudo apt-get -y install zlib1g-dev
  - sudo apt-get -y install libxslt1-dev
  - echo "Getting ProvPy..."
  - PROVPY=$PWD/ProvPy
  - git clone https://github.com/trungdong/prov $PROVPY
  - cd $PROVPY
  - git checkout 1.3.2
  - python setup.py install
  - ./scripts/prov-convert --version
  - cd ../..
  - TESTHARNESS=$PWD/test-harness
  - git clone https://github.com/mikej888/provtoolsuite-interop-test-harness $TESTHARNESS
  - cd $TESTHARNESS
  - pip install -r requirements.txt
  - echo "Creating local configuration files..."
  - echo "PROV_TEST_CASES_DIR=$TESTCASES" > config.properties
  - echo "PROVPY_SCRIPTS_DIR=$PROVPY/scripts" >> config.properties
  - echo "PROVTOOLBOX_SCRIPTS_DIR=$PROVTOOLBOX/toolbox/target/appassembler/bin" >> config.properties
  - echo "PROV_LOCAL_CONFIG_DIR=$TESTHARNESS/localconfig" >> config.properties
  - mkdir localconfig
  - python prov_interop/customise-config.py config localconfig config.properties
  - echo "Test configuration..."
  - cat localconfig/*

script: 
  - nosetests -v prov_interop.interop_tests.test_provpy
