# ProvPy interoperability tests
#
# This job assumes the following packages have been installed (these
# are provided by the Travis CI build environment,
# http://docs.travis-ci.com/user/ci-environment:
#
# git
# curl
# python 2.7 and 3.4
# graphviz 

language: python

python:
  - 2.7
  - 3.4

env:
  matrix:
    - TEST_TYPE=tests
#    - TEST_TYPE=interop_tests

addons:
  apt:
    packages:
    - zlib1g-dev
    - libxslt1-dev

before_install:
  - echo "Getting test harness..."
  - git clone https://github.com/mikej888/interop-test-harness
  - cd interop-test-harness
  - git checkout package
  - source scripts/install-prov-interop-comparator.sh
  - python setup.py install
  - cd ..
  - echo "Getting test cases..."
  - git clone https://github.com/prov-suite/testcases
  - echo "Getting ProvPy source..."
  - git clone https://github.com/trungdong/prov ProvPy
  - cd ProvPy
  - python setup.py install
  - prov-convert --version
  - prov-compare --version
  - cd ..

install:
  - python setup.py install
  
script: 
  - echo $TEST_TYPE
  - echo nosetests prov_interop_provpy.$TEST_TYPE
  - nosetests prov_interop_provpy.$TEST_TYPE > log.txt
